### ISSUE TITLE
[Bug] 前端在via浏览器上无法弹出播放器

### ISSUE THREAD

**Issue by yueziji** [hanaonnao/kikoeru-express#1]
**问题描述**
在安卓via上无法弹出播放器界面，没有播放也没有加载，其他较新版本的浏览器如Chrome108是可以的，但同内核的via不可以
换用了kikoeru-project/kikoeru-quasar(即旧版本)上的AudioPlayer.vue就可以正常弹出播放

**版本**
 - 系统：安卓
 - 安装方式：github编译安装
 - 浏览器：via
 - 版本：最新版本

**Comment by yueziji** [comment]
貌似调用系统webview的浏览器都不能弹出(

**Comment by hanaonnao** [comment]
因為在現有的kikoeru-quasar中，azuse添加了並使用了[mediaSession api](https://github.com/hanaonnao/kikoeru-quasar/commit/f542f1ad241581c092cd83b7c669eeb53fa53507)，而mediaSession在webview中是[不受支援](https://developer.mozilla.org/en-US/docs/Web/API/MediaSession#browser_compatibility)的。
您或許需要更改回未添加mediaSession api的AudioPlayer.vue以達到在Android WebView使用的功能。

**Comment by yueziji** [comment]
ok明白了谢谢
